// Challenge Mode types for Articard

import type { Rarity } from './database';

// Session status
// Note: 'deck_building' phase is now represented by status='in_progress' with currentPhase=0
export type ChallengeSessionStatus =
  | 'in_progress'
  | 'completed'
  | 'abandoned';

// Phase type determines card requirements
export type PhaseType = 'single' | 'combo' | 'triple';

// Phase definition in a scenario
export interface PhaseDefinition {
  phaseNumber: number;
  title: string;
  description: string;
  type: PhaseType;
  cardCount: number; // Number of cards to select (1 or 2)
  consumesCard: boolean; // Whether selected cards are marked as used
  baseScore: number; // Base points for this phase
}

// Scenario definition
export interface ScenarioDefinition {
  id: string;
  title: string;
  description: string;
  icon: string; // Emoji or icon identifier
  difficulty: 'easy' | 'normal' | 'hard';
  phases: PhaseDefinition[];
  totalPhases: number;
  deckSize: number;
}

// Challenge generated by AI for a phase
export interface PhaseChallenge {
  phaseNumber: number;
  title: string;
  situation: string; // The scenario situation
  challenge: string; // What the player needs to solve
  hint: string; // Optional hint for card selection
}

// Card evaluation result from AI
export interface CardEvaluation {
  fitScore: number; // 0-100
  bonusScore: number;
  totalScore: number;
  connectionExplanation: string; // Why this card works
  narrativeDescription: string; // Dramatic 3-5 sentence story
  humorComment: string; // Humorous commentary
}

// Scoring constants
export const RARITY_BONUS: Record<Rarity, number> = {
  common: 0,
  rare: 3,
  super_rare: 5,
  legend: 10,
};

export const PERFECT_FIT_THRESHOLD = 95;
export const PERFECT_FIT_BONUS = 10;

// Combo synergy bonus (when 2 cards work well together)
export const MAX_SYNERGY_BONUS = 10;

// Triple synergy bonus (when 3 cards work well together)
export const MAX_TRIPLE_SYNERGY_BONUS = 15;

// Score thresholds for different commentary styles
export const SCORE_THRESHOLDS = {
  HIGH: 90,
  MEDIUM: 60,
  LOW: 30,
} as const;

// Deck card in game state
export interface DeckCard {
  cardId: string;
  keyword: string;
  rarity: string;
  flavorText: string;
  contextDescription: string;
  thumbnailUrl: string;
  cardImageUrl: string;
  isUsed: boolean;
  usedInPhase: number | null;
}

// Phase result in game state
export interface PhaseResult {
  phaseNumber: number;
  challenge: string;
  selectedCardIds: string[];
  fitScore: number;
  bonusScore: number;
  totalScore: number;
  aiCommentary: string;
  completedAt: string;
}

// Session with deck and phase results (for API responses)
export interface ChallengeSessionWithDetails {
  id: string;
  userId: string;
  scenarioId: string;
  status: ChallengeSessionStatus;
  currentPhase: number;
  totalScore: number;
  startedAt: Date;
  completedAt: Date | null;
  deck: DeckCard[];
  phases: PhaseResult[];
}

// High score record
export interface ChallengeHighScore {
  scenarioId: string;
  highScore: number;
  bestRank: string;
  playCount: number;
  updatedAt: Date;
}

// Scenario list item (for selection page)
export interface ScenarioListItem {
  id: string;
  title: string;
  description: string;
  icon: string;
  difficulty: 'easy' | 'normal' | 'hard';
  totalPhases: number;
  deckSize: number;
  isAvailable: boolean;
}

// Display names
export const DIFFICULTY_DISPLAY_NAMES: Record<
  ScenarioDefinition['difficulty'],
  string
> = {
  easy: '簡単',
  normal: '普通',
  hard: '難しい',
};

export const SESSION_STATUS_DISPLAY_NAMES: Record<
  ChallengeSessionStatus,
  string
> = {
  in_progress: 'プレイ中',
  completed: '完了',
  abandoned: '中断',
};
